using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ShadowEmu.Common.Protocol.Enums
{
    public enum EmotesEnum : byte
    {
        NONE,
        EMOTE_S_ASSEOIR,
        EMOTE_S_ALLONGER = 19,
        EMOTE_CROISER_LES_BRAS = 14,
        EMOTE_MAINS_SUR_LES_HANCHES = 34,
        EMOTE_S_AGENOUILLER = 58,
        EMOTE_SE_PROSTERNER = 66,
        EMOTE_MONTRER_DU_DOIGT = 15,
        EMOTE_SALUER = 9,
        EMOTE_FAIRE_UN_SIGNE_DE_LA_MAIN = 2,
        EMOTE_FAIRE_UN_BISOU = 10,
        EMOTE_COUCOU = 49,
        EMOTE_ATTIRER_L_ATTENTION = 73,
        EMOTE_SALUT_VULKAIN = 65,
        EMOTE_GONFLER_SES_MUSCLES = 68,
        EMOTE_MONTRER_SON_ARME = 6,
        const_16 = 4,
        const_17 = 71,
        EMOTE_MONTRER_SA_PEUR = 5,
        EMOTE_FACEPAUME = 76,
        EMOTE_APPLAUDIR = 3,
        EMOTE_ENCOURAGER = 88,
        EMOTE_RIRE = 24,
        EMOTE_PLEURER = 26,
        EMOTE_REFUSER = 25,
        EMOTE_DOTS = 16,
        EMOTE_HALOUINE = 90,
        EMOTE_FLEURS = 35,
        EMOTE_MANOLIAS = 38,
        EMOTE_OFFRIR_UN_CADEAU = 56,
        EMOTE_LEVER_LE_POUCE = 43,
        EMOTE_BAISSER_LE_POUCE,
        EMOTE_PIED_DE_NEZ = 72,
        EMOTE_SUPER_HEROS = 51,
        EMOTE_PIOU = 48,
        EMOTE_SE_FROTTER_LES_MAINS = 75,
        const_36 = 36,
        const_37,
        EMOTE_AVOIR_FROID = 39,
        EMOTE_AVOIR_CHAUD = 67,
        EMOTE_MOTUS = 74,
        EMOTE_OGRINE = 70,
        const_42 = 8,
        EMOTE_TRACE = 33,
        const_44 = 7,
        const_45 = 92,
        EMOTE_LIRE_UN_LIVRE = 30,
        EMOTE_LIRE_UNE_CARTE = 69,
        EMOTE_LONGUE_VUE = 84,
        EMOTE_CHAMPION = 21,
        const_50 = 57,
        EMOTE_AURA_DE_PUISSANCE = 22,
        EMOTE_AURA_VAMPYRIQUE,
        const_53 = 40,
        EMOTE_AURA_DE_NELWEEN = 55,
        EMOTE_BOIRE_UNE_POTION = 61,
        const_56 = 18,
        EMOTE_MANGER = 17,
        EMOTE_FIOLE_DE_CHICHALA = 91,
        EMOTE_PIERRE = 11,
        EMOTE_FEUILLE,
        EMOTE_CISEAUX,
        const_62 = 63,
        EMOTE_STOK
    }
}
