using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ShadowEmu.Common.Protocol.Enums
{
    public enum ItemTypeEnum
    {
        NONE = -1,
        AMULET = 1,
        BOW,
        WAND,
        STAFF,
        DAGGER,
        SWORD,
        HAMMER,
        SHOVEL,
        RING,
        BELT,
        BOOTS,
        EXPERIENCE_SCROLL = 13,
        GIFT_ITEM,
        RESOURCE,
        HAT,
        CLOAK,
        PET,
        AXE,
        TOOL,
        PICKAXE,
        SCYTHE,
        DOFUS,
        MISCELLANEOUS,
        DOCUMENT,
        SMITHMAGIC_POTION,
        MUTATION_ITEM,
        BOOST_FOOD,
        BLESSING,
        CURSE,
        ROLEPLAY_BUFF,
        FOLLOWING_CHARACTER,
        BREAD,
        CEREAL,
        FLOWER,
        PLANT,
        BEER,
        WOOD,
        ORE,
        ALLOY,
        FISH,
        CANDY,
        SPELL_DELEVELING_POTION,
        PROFESSION_DELEVELING_POTION,
        WEAPON_SKILL_DELEVELING_POTION,
        FRUIT,
        BONE,
        POWDER,
        EDIBLE_FISH,
        PRECIOUS_STONE,
        STONE,
        FLOUR,
        FEATHER,
        HAIR,
        FABRIC,
        LEATHER,
        WOOL,
        SEED,
        SKIN,
        OIL,
        STUFFED_TOY,
        GUTTED_FISH,
        MEAT,
        PRESERVED_MEAT,
        TAIL,
        METARIA,
        VEGETABLE = 68,
        EDIBLE_MEAT,
        DYEING,
        ALCHEMY_EQUIPMENT,
        PET_EGG,
        SKILL,
        FAIRYWORK,
        SPELL_SCROLL,
        CHARACTERISTIC_SCROLL,
        PET_CERTIFICATE,
        SMITHMAGIC_RUNE,
        DRINK,
        MISSION_ITEM,
        BACKPACK,
        SHIELD,
        SOUL_STONE,
        KEYS,
        FULL_SOUL_STONE,
        PERCEPTOR_DELEVELING_POTION,
        SEEKER_SCROLL,
        MAGIC_STONE,
        GIFT,
        PET_GHOST,
        DRAGOTURKEY,
        GOBBALL,
        BREEDING_ITEM,
        USABLE_ITEM,
        PLANK,
        BARK,
        MOUNT_CERTIFICATE,
        ROOT,
        CAPTURING_NET,
        BAG_OF_RESOURCES,
        CROSSBOW = 102,
        LEG,
        WING,
        EGG,
        EAR,
        CARAPACE,
        BUD,
        EYE,
        JELLY,
        SHELL,
        PRISM,
        LIVING_OBJECTS,
        MAGIC_WEAPON,
        FRAGMENT_OF_SHUSHU_SOUL,
        PET_POTION,
        EQUIPMENT = 118,
        MUSHROOM,
        PETSMOUNT = 121,
        PETSMOUNT_POTION,
        PETSMOUNT_CERTIFICATE,
        PETSMOUNT_GHOST,
        SOUVENIR,
        MAIN_QUESTS,
        TEMPLE_QUESTS,
        WANTED_NOTICES,
        ALIGNMENT,
        CITY_ORDERS,
        EVENTS,
        ARCHIPELAGO_OF_VULKANIA,
        ASTRUB,
        CITY_QUESTS,
        BWORK_CAMP = 136,
        CANIA,
        AMAKNA_CASTLE,
        FRIGOST_ISLAND,
        OTOMAI_ISLAND,
        KWISMAS_ISLAND,
        INCARNAM,
        KOALAK_MOUNTAIN,
        PANDALA,
        MADRESTAM_HARBOUR,
        PROVINCE_OF_AMAKNA,
        KROSMOZ,
        TOKENS,
        MOON_ISLAND,
        WABBIT_ISLAND,
        TROPHY,
        PEBBLE,
        KWISMAS,
        WRAPPING_PAPER,
        END,
        POTION = 211
    }
}
