using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ShadowEmu.Common.Protocol.Enums
{
    public enum PlayerFields : byte
    {
        Health = 1,
        Initiative,
        Prospecting,
        AP,
        MP,
        Strength,
        Vitality,
        Wisdom,
        Chance,
        Agility,
        Intelligence,
        Range,
        SummonLimit,
        DamageReflection,
        CriticalHit,
        CriticalMiss,
        HealBonus,
        DamageBonus,
        WeaponDamageBonus,
        DamageBonusPercent,
        TrapBonus,
        TrapBonusPercent,
        PermanentDamagePercent,
        TackleBlock,
        TackleEvade,
        APAttack,
        MPAttack,
        PushDamageBonus,
        CriticalDamageBonus,
        NeutralDamageBonus,
        EarthDamageBonus,
        WaterDamageBonus,
        AirDamageBonus,
        FireDamageBonus,
        DodgeAPProbability,
        DodgeMPProbability,
        NeutralResistPercent,
        EarthResistPercent,
        WaterResistPercent,
        AirResistPercent,
        FireResistPercent,
        NeutralElementReduction,
        EarthElementReduction,
        WaterElementReduction,
        AirElementReduction,
        FireElementReduction,
        PushDamageReduction,
        CriticalDamageReduction,
        PvpNeutralResistPercent,
        PvpEarthResistPercent,
        PvpWaterResistPercent,
        PvpAirResistPercent,
        PvpFireResistPercent,
        PvpNeutralElementReduction,
        PvpEarthElementReduction,
        PvpWaterElementReduction,
        PvpAirElementReduction,
        PvpFireElementReduction,
        GlobalDamageReduction,
        DamageMultiplicator,
        PhysicalDamage,
        MagicDamage,
        PhysicalDamageReduction,
        MagicDamageReduction,
        WaterDamageArmor,
        EarthDamageArmor,
        NeutralDamageArmor,
        AirDamageArmor,
        FireDamageArmor,
        Erosion,
        Shield,
        GlyphBonus,
        GlyphBonusPercent, 
        HealMultiplicator,
        BonusPano,
        SpellBoost,
        BombBonus,
        FinalDamage,
        Unknow
    }
}
